services:
  graph_ql:
    container_name: graph_ql
    build: .
    ports:
      - "8000:8000"
    networks:
      - my_network


  dictionary_service:
    image: ruzzik/kalimeros_dictionary:latest
    container_name: dictionary_service
    networks:
      - my_network
    depends_on:
      - db_dict

  db_dict:
    image: postgres:15
    container_name: dictionary_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: dictionary
    ports:
      - "5432:5432"
    volumes:
      - pgdata_dict:/var/lib/postgresql/data
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  pgdata_dict:
