# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protobuf/dictionary_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'protobuf/dictionary_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!protobuf/dictionary_service.proto\"D\n\x0e\x41\x64\x64WordRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04word\x18\x02 \x01(\t\x12\x13\n\x0btranslation\x18\x03 \x01(\t\"7\n\x0f\x41\x64\x64WordResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2A\n\x11\x44ictionaryService\x12,\n\x07\x41\x64\x64Word\x12\x0f.AddWordRequest\x1a\x10.AddWordResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.dictionary_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDWORDREQUEST']._serialized_start=37
  _globals['_ADDWORDREQUEST']._serialized_end=105
  _globals['_ADDWORDRESPONSE']._serialized_start=107
  _globals['_ADDWORDRESPONSE']._serialized_end=162
  _globals['_DICTIONARYSERVICE']._serialized_start=164
  _globals['_DICTIONARYSERVICE']._serialized_end=229
# @@protoc_insertion_point(module_scope)
